language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed buixuandai/udagram-api-feed:v1
  - docker tag udagram-api-user buixuandai/udagram-api-user:v1
  - docker tag udagram-frontend buixuandai/udagram-frontend:v1
  - docker tag reverseproxy buixuandai/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push buixuandai/udagram-api-feed:v1
  - docker push buixuandai/udagram-api-user:v1
  - docker push buixuandai/udagram-frontend:v1
  - docker push buixuandai/reverseproxy:v1