apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: buixuandai/udagram-api-feed:v1
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-password
              key: db-password
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres-user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres-db
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: postgres-host
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws-region
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws-profile
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: aws-bucket
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret
        ports:
        - containerPort: 8080